server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#configurando a quantidade de tentativas de acesos ao serviço
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 3
#Limita as requisições para 2 no tempo de 10 segundos
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
# configuracao para quantidade de tentativas de requisicao em caso de falhas
  retry:
    instances:
      default:
        max-attempts: 5
        wait-duration: 5
        enable-exponential-backoff: true
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book_service?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: postgres
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect